name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ftp.boarttaxi.com.ua >> ~/.ssh/known_hosts

      - name: Create .env file from secrets
        run: |
          echo "APP_ENV=production" > .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "ORCHID_ADMIN_PASS=${{ secrets.ORCHID_ADMIN_PASS }}" >> .env

      - name: Sync files to server
        run: |
          rsync -avz --delete --exclude '.env' --exclude 'storage/' --exclude 'vendor/' ./ jbqbtqee@ftp.boarttaxi.com.ua:/home/jbqbtqee/public_html/
          rsync -avz .env jbqbtqee@ftp.boarttaxi.com.ua:/home/jbqbtqee/public_html/.env

      - name: Ensure storage and cache directories exist and set permissions
        run: |
          ssh jbqbtqee@ftp.boarttaxi.com.ua '
            cd /home/jbqbtqee/public_html &&
            mkdir -p storage/framework/cache/data &&
            chmod -R 775 storage/framework/cache
          '

      - name: Run remote commands
        run: |
          ssh jbqbtqee@ftp.boarttaxi.com.ua '
            cd /home/jbqbtqee/public_html &&
            composer install --no-dev &&
            php artisan migrate --force &&
            php artisan orchid:link &&
            php artisan cache:clear &&
            php artisan config:cache &&
            php artisan route:cache &&
            php artisan view:clear
          '

      - name: Set permissions
        run: |
          ssh jbqbtqee@ftp.boarttaxi.com.ua '
            cd /home/jbqbtqee/public_html &&
            find storage -type d -exec chmod 775 {} \; &&
            find storage -type f -exec chmod 664 {} \; &&
            chmod -R 775 bootstrap/cache
          '
